bsnes/target-libretro/libretro.cpp
I'm looking to move the libretro fork's parent over to this repo, since the original parent is now gone and I assume this is where the action will be taking place from here on out. This is the one commit we had locally that wasn't upstream, so I figured I'd offer it up: https://github.com/libretro/bsnes/commit/f04fe9bf5bfe8fc6a3ce3ee2c90747daf579258c
=> Consider the overscan setting when getting the aspect ratio

nall/GNUmakefile
```
* WARNING: Backward-incompatibility!
Previously appending using '+=' to an empty variable would result in a value
starting with a space.  Now the initial space is only added if the variable
already contains some value.  Similarly, appending an empty string does not
add a trailing space.
```
https://lwn.net/Articles/810071/
Should be applied to all copies of nall across both @bsnes-emu and @higan-emu, as well as Near's upstream (do you have his contact info?).
=> GNU Make 4.3 compatibility

bsnes/target-libretro/libretro.cpp, bsnes/target-libretro/program.cpp
This adds support for the BS-X Satellaview to the libretro port. It works similarly to Super Game Boy.
=> libretro: Add support for BS-X Satellaview

.github/workflows/build.yml
This is lightly adapted from the implementation in Higan. For more information, see that PR in higan-emu/higan#118.
The main difference is that we only compile one binary here, and packaging is similar to (but adapted from) packaging `byuu`.
Nightly release: https://github.com/jchw-forks/bsnes/releases/tag/nightly
Test tagged release: https://github.com/jchw-forks/bsnes/releases/tag/v116
(Note: I haven't done any serious testing to ensure that the binaries are correct yet, since none of them will run on the NixOS box that I am typing this message from.)
Fixes #72.
=> Implement GitHub Actions Based CI.

bsnes/target-bsnes/tools/cheat-editor.cpp
Previously, bsnes would turn the cheat text into a list of cheats by splitting on '\n', producing an empty "cheat" after the last line of the editor:
"7e0003=00\n".split("\n") -> ["7e0003=00", ""]
That empty "cheat" is not a valid cheat, so the result would be marked invalid. Teaching bsnes to silently skip empty lines worked, but it would preserve multiple blank lines between two cheats, which was silly.
Now we iterate over all the lines of the cheat editor, putting valid codes in a new vector, and setting a flag for invalid codes.
This fix works for me, but I would particularly appreciate code-review from people who understand C++ memory-management - in Rust you can't move items from one vector to another unless iterating over the old vector consumes it and will release its memory; it's …
=> Strip whitespace and empty lines from the cheat editor.

LICENSE.txt, bsnes/emulator/emulator.hpp
Previously, we didn't have control of byuu.org and it wasn't obvious what we should do about hosting. Now we can update byuu.org, though, we should continue using it as the authoritative source information.
Fixes #2.
=> Use byuu.org/bsnes as the official homepage.

bsnes/sfc/cpu/cpu.hpp, bsnes/sfc/cpu/io.cpp, bsnes/sfc/cpu/timing.cpp, bsnes/sfc/interface/configuration.cpp, bsnes/sfc/interface/configuration.hpp, bsnes/target-bsnes/program/hacks.cpp, bsnes/target-libretro/program.cpp
This merges SNES auto-joypad polling fixes. The new code runs the auto-joypad polling at 128-cycle granularity instead of 256-cycle granularity, so that the first event can happen ~128 cycles after the start of Vblank. I've left comments for the unknown behaviors. I also removed the hacks since they are no longer needed.
This fixes issue 3 of 3 for https://github.com/bsnes-emu/bsnes/issues/61, which means we can close issue 61 now.
I have tested and confirmed these fixes work with every game affected.
=> Fix auto-joypad polling

nall/intrinsics.hpp
Also, moved the snippet that includes endian.h beneath the "Endian detection" header, since I think it fits more neatly there.
Fixes #77.
=> nall: Support all the names endian.h provides on common platforms.

bsnes/target-bsnes/presentation/presentation.cpp
In f09c45f, we fixed native file picker dialogs, so they would correctly set the "option" field to Auto when loading games, instead of leaving it set to an empty string which effectively forced NTSC mode. However, this wouldn't fix up the old entries in the Recent Games menu, so we will patch them up if we encounter them.
=> target-bsnes: Patch up broken recent-game entries.

bsnes/target-bsnes/bsnes.cpp, bsnes/target-bsnes/program/program.cpp, bsnes/target-bsnes/settings/emulator.cpp, bsnes/target-bsnes/settings/settings.hpp, hiro/cocoa/application.cpp
Fixes #87.
This PR implements the missing hiro/cocoa functionality to make this feature work on macOS and makes the setting configurable in the UI. Additionally, because I felt it doesn't make sense to suppress screensavers when nothing is loaded, I made some changes so the feature only kicks in when emulation is active.
=> target-bsnes: Rework screensaver suppression

bsnes/target-bsnes/settings/input.cpp
-   Fixes a bug where the program may crash or display improper buttons when changing the selected row during assignment.
This appears to just be a mistake, accidentally using the 'batched' rows instead of the activeMapping row.
-   Fixes a bug where starting multiple assignments without finishing one leads to stale "Assigning..." text in some rows.
This appears to be an oversight. Simply refreshing the mappings before starting an assignment fixes this.
This patch should supersede #95 if testing proves that it works as intended across all platforms as it is more straightforwardly-correct (this fixes not only a crash, but also a logical error that can lead to at least one impossible assignment.)
| Before | After |
| --- | --- |
| ![Animation displaying several input bugs as described …
=> target-bsnes: Fixes for a couple of input settings bugs.

bsnes/sfc/cpu/io.cpp
This corrects the reporting bit of HVBJOY to be set during the auto joypad polling sequence.
This change will fix *SpellCraft - Aspects of Valor*. SpellCraft works by polling JOY1 nonstop once menus are entered on every scanline, so with incorrect HVBJOY bit 0 reporting, the game was thinking it was safe to read JOY1 during the auto joypad polling sequence, so partially shifted in results were being read back as valid. With this patch, you'll find that the game stops polling between V:225 H:130 and V:228 H:256, which is the auto polling time range. Before, it was polling during that time. As a result of this fix, the password menu can be accessed safely without it closing immediately.
Fixes #86.
=> sfc: Report auto joypad polling in the HVBJOY register.

hiro/gtk/application.cpp, hiro/qt/application.cpp
On X11, hiro uses the xdg-screensaver helper tool to disable the screensaver, which detects the screensaver that is running and uses the appropriate mechanism to communicate with it. The tool's API expects an X11 window ID,
but at least some screensavers ignore it, so it can be set up however. The GNOME backend *does* care about the window ID, but its expectations are not documented anywhere, so byuu spent a frustrating few days trying things at random to get it working, and failing.
It turns out, GNOME does *not* require the window to be mapped, but it *does* require the window to have a name. Using XStoreName() to name the window fixes screensaver suspension for me under GNOME 3.38.
Note: while XStoreName is technically deprecated, it's not going to go away while X11 is still around, …
=> hiro: Fix screensaver suspension under GNOME on X11.

bsnes/target-bsnes/presentation/presentation.cpp, bsnes/target-bsnes/presentation/presentation.hpp
To resize a window on X11, the window manager tells the X11 server to change the window size, then the X11 server tells the application to paint itself, and then (eventually) the application tells the X11 server what to draw. This adds an arbitrary amount of latency to resizing, so to make things feel more responsive, the X11 server will paint any newly-exposed parts of the window with a default background colour. If it happens to be the same colour as the appplication would paint anyway, this gives resizing a much better user-experience.
Since most of bsnes' window is occupied by the viewport, which is always black, bsnes accordingly set its window background colour to black for the best resizing experience. However, this had two additional effects:
- When no game is loaded, bsnes …
=> target-bsnes: Do not set the window background to black.

bsnes/emulator/emulator.hpp
I've registered https://bsnes.dev to be the new homepage for the project.
Screwtape and I are still working out how we're going to handle the page, but I want to get away from the old domain, and this is where we start that process.
=> Update website and copyright

.cirrus.yml
Apparently Ports only supports the latest stable release, not earlier releases in the 12.x family.
=> Update the FreeBSD image to fix a build failure.

ruby/GNUmakefile
For source builds its annoying and brittle having to write `sed` commands to automatically remove these from `ruby/GNUmakefile` when the dependencies are not present.
I think its better doing this directly in the build system with `pkg-config --exists`.
This will automatically detect and enable if present:
* sdl2
* openal
* pulseaudio
* libao
* udev
This also only applies to linux builds, other platforms may want to do similar, but I will leave that for people who actually use them.
=> ruby: Auto detect some dependencies on linux.

.cirrus.yml, .github/workflows/build.yml, hiro/GNUmakefile, hiro/components.hpp
The GTK2 and GTK3 backends for hiro implement a source-code editing widget based on gtksourceview. gtksourceview2 in particular is quite old and unmaintained, and Linux distros are keen to drop it, so removing the dependency helps keep bsnes portable to future platforms -- especially since bsnes doesn't *use* the source-editing widget anywhere. It's only used by Near's text-editor, amethyst.
We could just rip out the gtksourceview-related code and be done with it, but since Near is still around and still working on his own copy of hiro, I asked him to contribute his implementation so that it will be easier to merge any future changes too.
This adds two new hiro targets, "gtk2-se" and "gtk3-se" which include the source-code editing widget and the gtksourceview dependency. Since bsnes …
=> hiro: Remove gtksourceview dependency.

hiro/gtk/application.cpp
GTK+3 is designed for automatic layout, where widgets are automatically sized and positioned according to the size of their contents. However, hiro has to be compatible with Windows, which lacks an automatic layout system, so hiro apps tend to position widgets manually.
Unfortunately, the GTK+3 default theme uses much bigger widgets than GTK+2 or Windows, so hiro apps using the GTK+3 backend tend to have ugly, overlapping widgets. To make GTK+3 behave more like other hiro targets, we add custom CSS and override the default theme at runtime.
Fixes #168.
How the Drivers pane currently looks in GTK+2:
How the Drivers pane currently looks in GTK+3:
How the Drivers pane looks with this PR:
There's a status-bar at the bottom of the Settings window whose top overlaps the bottom of the pane list, …
=> hiro: Disable padding for the GTK+3 backend.

bsnes/sfc/cpu/cpu.hpp, bsnes/sfc/cpu/io.cpp, bsnes/sfc/cpu/serialization.cpp
Jonas Quinn refactored higan's auto-joypad polling in https://github.com/higan-emu/higan/commit/e422ddc7293b10aae8a1935d4c7f96aeb8445430, then Asura re-implemented those changes for bsnes in 39c37ec. A bug was found in bsnes, fixed in 4f7a269, and Jonas Quinn ported the bsnes version of the code back to higan in https://github.com/higan-emu/higan/commit/9a625c545ca89b094d5c1da40bbfa5d07156a4aa.
In the process of that (back?) port, Jonas discovered that the `autoJoypadActive` and `autoJoypadLatch` variables were no longer actually being used in bsnes. Also, Jonas' original patch taught higan what happens when auto-joypad polling is disabled while active, and that detail had not made it across to bsnes before.
With these changes, bsnes and higan should once again be equally accurate …
=> Auto joypad cleanup

nall/primitives/bit-range.hpp
Natural/Integer<T>.bit() (BitRange) was shifting by whatever type the source was to match the target bit length.
But this breaks when the target type is u64/s64 and the source type is u32/s32 or smaller. Shifting by >=32 becomes undefined behavior.
We have to cast the input source to the target type first, so that the source<<shift result is valid.
This is safe here regardless of source's signedness, because it's only used in =, &=, ^=, |= operations.
Cherry-picked from https://github.com/higan-emu/higan/pull/174/files
=> Fix critical undefined bit-shift length operation

nall/vector.hpp, nall/vector/memory.hpp
This would fail to compile previously because `_pool`, which is of type `T*`, is assigned a variable of type `const T*` which results in a compiler error.
Note that this does not affect bsnes at all because this function is unused.
=> Fix vector<T>::acquire() arguments

README.md
With Near's death, we no longer have access to update https://bsnes.dev, so we'll need to put links in the README now.
=> Add a link to the official Discord.

nall/inode.hpp, nall/intrinsics.hpp
This is a manual backport of this commit from the upstream `nall` repository:
https://github.com/higan-emu/nall/commit/c673bd802e84050d83cb977955550947dccf9aef
Since the copy of `nall` in `bsnes` has diverged from the upstream repository, simply importing upstream `nall` is not possible without some changes deep in the `bsnes` codebase. Until those changes happen, this commit gives us out of the box OpenBSD support, while also paving the way for out of the box support for DragonFly.
=> nall: File timestamp fix for OpenBSD and DragonFly BSD, add DragonFly BSD to PLATFORM_BSD definition

ruby/audio/audio.cpp
Same order as defined in ares, which favor pulseaudio over ALSA.
=> Reorder optimal audio drivers

ruby/input/mouse/quartz.cpp, ruby/input/quartz.cpp
While keyboard and joypad input had already been present for some time, mouse input for macOS remained unimplemented in ruby.
Until now, that is.
Fixes #222.
=> ruby/input: Add macOS mouse support

bsnes/sfc/coprocessor/sa1/io.cpp
Removes the branch and the double modulo
I have verified that it gives the same results for all 2^32 pairs of inputs
=> Simplify sa1 division

nall/arithmetic/natural.hpp
```
Compiling hiro/hiro.cpp ...
In file included from ../nall/arithmetic.hpp:37,
from ../nall/hash/hash.hpp:3,
from ../nall/hash/sha256.hpp:3,
from ../nall/file-buffer.hpp:12,
from ../nall/file.hpp:3,
from ../nall/directory.hpp:3,
from ../hiro/core/core.hpp:4,
from ../hiro/core/core.cpp:13,
from ../hiro/hiro.cpp:5:
../nall/arithmetic/natural.hpp: In function 'void nall::div(const uint256_t&, const uint256_t&, uint256_t&, uint256_t&)':
../nall/arithmetic/natural.hpp:239:23: error: 'runtime_error' is not a member of 'std'
239 |   if(!rhs) throw std::runtime_error("division by zero");
|                       ^~~~~~~~~~~~~
../nall/arithmetic/natural.hpp:1:1: note: 'std::runtime_error' is defined in header '<stdexcept>'; did you forget to '#include <stdexcept>'?
+++ |+#include <stdexcept>
1 | …
```
=> nall: Fix the build for gcc13

nall/arithmetic.hpp
This reverts commit e658f50da2f0b142f672452abad987341e81efd4.
bsnes' compatibility with GCC 13 was already fixed in a different way in 5cefce5c08f74cfc80eee3f82a32d846144e5277.
=> Revert "nall: Add needed #include <stdexcept>"

bsnes/target-libretro/libretro.cpp, bsnes/target-libretro/program.cpp
This adds support for all four of blargg's NTSC filter options to the libretro port of bsnes.
As a consequence of using the filter functionality, the pixel format has been changed to XRGB8888 (preferable to the awkward 0RGB1555 when considering cross-platform compatibility and it is seemingly deprecated anyway). It also now builds on musl-libc without patches.
Closes #289
=> libretro: Support blargg's NTSC filter

bsnes/target-libretro/libretro.cpp
I did not implement correct support for filters when "subsystems" are loaded in my previous commit. This one fixes this issue and ensures when loading via the "subsystem" option, the filters will apply correctly.
=> libretro: Correctly apply filters for subsystems

bsnes/processor/wdc65816/instructions-other.cpp
Cherry-picked https://github.com/ares-emulator/ares/commit/e589f8d9cf1aaf04b1959bfc7d7085cb3861149c.
I've checked and confirmed this does fix the test in question.
Note that this does not fix the additional tests from [version 1.2](https://github.com/gilyon/snes-tests/releases/tag/v1.2) of the cpu test rom.
=> wdc65816: fix PLB wrapping in emulation mode

.github/workflows/build.yml
- Update steps to latest action versions
- Use GitHub script (Node.JS + Octokit.js) step to:
- Try to delete old release.
- Try to delete old tag.
- Create new nightly tag for release.
- Use `softprops/action-gh-release` to actually create the releases.
- GitHub has officially recommended this action in the deprecated official `upload-release-asset` action.
- It seems like what it does is complicated enough to warrant actually using a third-party action instead of rolling our own.
The hope is that using Octokit.js will buy us a lot of time, as the API should be very stable at this point in time. Even if the GitHub API shifts, these fairly high-level calls shouldn't need to break much if at all, and I think the stuff this script does are complicated enough to warrant avoiding bash for the …
=> Simplify + update GitHub Actions workflow

bsnes/heuristics/super-famicom.cpp
The Sufami Turbo base cartridge is listed in the Super Famicom verified dump database, so it did not use the heuristics. It turns out the heuristic detection wouldn't have worked anyway - although the game's header does contain the serial A9PJ, the heuristic revision() method does not report that serial at all.
Meanwhile, the serial A9PJ is *also* used by the game Bishoujo Senshi Sailor Moon SuperS - Fuwafuwa Panic, so loading this game would prompt for Sufami Turbo mini-cartridges even though the game could not make use of them.
Fixes #323
=> Fix detection of the Sufami Turbo base cartridge.

bsnes/heuristics/super-famicom.cpp
Commit 712ed9b6b0d7aa00919738335d586c21fa9221c6 changed the way that the Sufami Turbo base cartridge was detected, but it caused crashes. Apparently the way we were converting the binary ROM data to a string for comparison, was actually calling the wrong `string` constructor. Let's more explicitly create a string_view instead of hoping for the compiler to pick a suitable constructor chain.
=> Fix a crash in heuristic memory mapping.

nall/string/cast.hpp
Many specializations of stringify store a reference to the wrapped value. Therefore, passing arguments to make_string() by value can be disastrous if the compiler does not perform copy elision and stringify stores a reference to a variable that goes out of scope when make_string() returns.
Cherry-picked from ares commit 3d826f5b266027529f0c12211c744a23bbe25a56.
Because bsnes was missing this fix, my first attempt at preventing *Bishoujo Senshi Sailor Moon SuperS - Fuwafuwa Panic* from being detected as a Sufami Turbo base cartridge was caused a crash. Hat tip to SuperMikeMan100 on Discord for pointing it out.
=> nall: always pass by reference to make_string()

bsnes/sfc/coprocessor/sa1/iram.cpp
Logic is based on [what ares does](https://github.com/ares-emulator/ares/blob/d6858ad8219a031a02dd4c91f90f69be6349b1ee/ares/sfc/coprocessor/sa1/iram.cpp).
I've checked with the testrom from https://github.com/absindx/SNES-TestRoms/tree/a229ee7215effdd1d21ef70dbcb15694ac4d8046/SA1RamProtectionTest and have confirmed that bsnes now passes all tests.
=> Implement SA1 I-RAM write protection

bsnes/sfc/coprocessor/sa1/dma.cpp
Adds the update mentioned in bug #309
=> Fix for SA-1 DMA to BWRAM banks 0x41+

bsnes/emulator/emulator.hpp, bsnes/sfc/cpu/cpu.hpp, bsnes/sfc/cpu/io.cpp, bsnes/sfc/cpu/serialization.cpp, bsnes/sfc/cpu/timing.cpp
This fixes #322.
In addition, these changes improve results in a number of test roms from https://github.com/bsnes-emu/bsnes/issues/322#issuecomment-2952297191.
Most of these test roms aren't "good or bad" and instead show trends and general behavior. In some cases it's clear when the emulator behavior is wrong and in other cases it's not so clear. The displayed values are not fixed and change frame-by-frame. I think it is most important to *roughly* match the hardware result. In some cases there may not even be one true correct result as even different hardware differs in results.
That being said, on current master the following tests are **clearly bad**:
```
01 auto-joy-timing-test
05 blip-autojoy-test-automatic
06 enable-autojoy-late-test-2
07 blip-autojoy-test
08 …
```
=> Improve auto-joypad polling timing

bsnes/emulator/emulator.hpp
The registration for bsnes.dev has lapsed a long time ago, the GitHub repo is effectively the website now.
Fixes #354
=> Make the About dialog link to a website that exists.

hiro/qt/desktop.cpp
Qt 5.0 adds the QScreen API, which exposes enough information that `Desktop::{size,workspace}` no longer needs to fall back to Win32/Xlib. I manually tested that this seems to give the same exact answers as the Xlib path with multi-monitor/hidpi on KDE Plasma (though it technically goes a different route for `Desktop::size`.)
Since this API doesn't exist until Qt 5.0, this breaks the Qt 4 build. However, Qt 4 is long dead now. Even if we wanted to test it and keep it working, it would be hard since no recent distro releases ship Qt 4. Instead of bifurcating this any further, I think the right thing to do is just drop Qt 4 support and remove all of the legacy Qt 4 paths for once and for all: #361
Mirrored in:
- ares: https://github.com/ares-emulator/ares/pull/2189
- higan: …
=> Use QScreen for `Desktop::{size,workspace}`
